Custom Heirarchical Time series forecasting with Azure Automl
microsoft/forecasting pull request #233
Opened 2021-11-11 18:41 UTC by Jash271

### Description

So what was really happening with hierarchical time series forecasting is that I wanted forecast for a very niche query and had to wait for almost 3-4 hours of the model to train over a dataset that was barely even 20MB
Plus creating additional compute instances and all was quite a headache and not to forget getting predictions too was very time-consuming. It was like I wanted answers for a very small sample combination (like forecast for store 3,dept 6,state California ) but had to wait for training on other combinations as well. Hence I created a class-based solution that makes use of the classic time-series forecasting service of azure and rather trains it only on the Hierarchical combination the user wants predictions for I feel this whole thing could be converted into a proper Azure service with a frontend to render graphs and an SDK as well.

Kindly let me know what you feel about this solution.I am open to discussing the implications of the same and would like to know your feedback as well.

** There might be a lot of scope for correction and improvement in the solution that I've created. Let me know your feedback about this as well, where I could have made this more efficient or could have made the process even more optimal.

### Related Issues

### Checklist:

- [x] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [ ] I have added tests.
- [] I have updated the documentation accordingly.

2021-11-15 17:58 UTC, chenhuims commented
@Jash271 Thank you for your PR! I will be very happy to review it.

2021-11-15 21:13 UTC, Jash271 commented
So yhank you kuch graduate  know my code isn't really perfect,but I would love to know your feedback on where I could improve,or perhpas make this whole process even more optmized.
Incase if you'll do go ahead with this idea for the service or the sdk(I would love to contribute towards it's development).I just hope my solution happens to serve as a good starting point.

2021-11-15 22:24 UTC, chenhuims requested changes

2021-11-15 22:24 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Custom Heirarchical Time Series Forecasting.ipynb
> +   "source": [
Please explain the main contribution of this notebook and each step that you perform by adding markdown cells in the notebook.

2021-11-15 22:24 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +## This is a class based solution aimed to solve the problem of heirarchical time series forecasting requiring expensive compute resources and takes a lot of time to train with basic computing resour
The font size here is too big. I suggest that you remove unnecessary headers ## or ### in the main body.

2021-11-15 22:24 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Custom Heirarchical Time Series Forecasting.ipynb
> +       "0  2012-11-02 44586.91 47054.11 48976.38 48065.81\n",
Why there are many nan values in the results? Can you further evaluate the accuracy of the forecasts quantitatively?

2021-11-16 04:15 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### [The dataset used here is of Wallmart hiring challenge contest](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting)
Ooh,so in that case we can use Microsoft's Dataset that's provided with hierarchical time series forecasting dataset in their MachineLearning Notebooks repository : https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-hierarchical-timeseries/Data

2021-11-16 04:16 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/runner.py
> +import numpy as np
Yes,I'll remove this python file .I created a seperate file to isolate the solution from its results as shown in the notebook.Nonetheless,I'll remove the python file

2021-11-16 04:17 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Custom Heirarchical Time Series Forecasting.ipynb
> +   "source": [
Yes,I'll add in the comments,as in the idea I am implementing.Perhaps I'll keep this structure : 
Problem
My idea
Code with implementation

2021-11-16 04:17 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +## This is a class based solution aimed to solve the problem of heirarchical time series forecasting requiring expensive compute resources and takes a lot of time to train with basic computing resour
Okay,I'll refactor the readme.md

2021-11-16 04:20 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Custom Heirarchical Time Series Forecasting.ipynb
> +       "0  2012-11-02 44586.91 47054.11 48976.38 48065.81\n",
We'll,I am also not sure why there were nan values and they happened to appear only for 75th and 99th percentile.I 'll have a look at it again and as far as comparing the accuracy goes - I'll have to compare both the approaches but I fear I don't have enough credits left to experiment with a higher computational resource

2021-11-16 04:21 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Custom Heirarchical Time Series Forecasting.ipynb
> +       "0  2012-11-02 44586.91 47054.11 48976.38 48065.81\n",
Nonetheless,I'll make all the required changes and get back.Thank you @chenhuims

2021-11-16 16:44 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +## This is a class based solution aimed to solve the problem of heirarchical time series forecasting requiring expensive compute resources and takes a lot of time to train with basic computing resour
@chenhuims , 
Hello Sir,as per your feedback I have added the comments and have refactored the code.
Do let me know f you feel anything's missing or there are any more changes to be done and perhaps your feedback on this approach and maybe if I could optimize this even further.

Sir,I have planned out how this forecasting thing can be converted into an Azure web service

2021-11-23 13:38 UTC, Jash271 commented
@chenhuims ,Sir any updates ?

2021-11-23 15:04 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### [The dataset used here is of Wallmart hiring challenge contest](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting)
Yea, I think the dataset used in the Azure MachineLearning Notebooks repository is a better option. Could you update your code by using this dataset?

2021-11-23 15:09 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/runner.py
> +import numpy as np
Sounds good

2021-11-23 15:16 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### [The dataset used here is of Wallmart hiring challenge contest](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting)
Yes sir,already updated

2021-11-23 15:16 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/runner.py
> +import numpy as np
Yes sir,I've made all the required changes in this pr

2021-11-23 15:41 UTC, chenhuims requested changes

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +# Custom Heirarchical Time Series Forecasting
Maybe use this title 'AzureML Custom Hierarchical Time Series Forecasting' to highlight the usage of AzureML. Also there is a typo in 'Heirarchical'.

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### Using a standard compute resource (STANDARD_DS11_V2) and traning the model over the dataset provided in the Data folder,took more than 3 hours to train the model.As per the [documentation](https:
Please remove ### in the beginning. Similar comments for all the paragraphs below.

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### Using a standard compute resource (STANDARD_DS11_V2) and traning the model over the dataset provided in the Data folder,took more than 3 hours to train the model.As per the [documentation](https:
It would be great to start with describing the hierarchical forecasting problem and why you use AzureML so that audience knows the context better.

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### What really happens is that I dynamically slice the dataset basis the heirarchy variables the user passes upon which it requires the forecast for,then using the sliced dataset I train the model a
basis -> based on

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### What really happens is that I dynamically slice the dataset basis the heirarchy variables the user passes upon which it requires the forecast for,then using the sliced dataset I train the model a
give out predictions for the same -> generate forecasts

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### What really happens is that I dynamically slice the dataset basis the heirarchy variables the user passes upon which it requires the forecast for,then using the sliced dataset I train the model a
heirarchy -> hierarchy. Please also check possible typos in other places.

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### What really happens is that I dynamically slice the dataset basis the heirarchy variables the user passes upon which it requires the forecast for,then using the sliced dataset I train the model a
Did you add this additional caching feature? If so, you can point it out that this is another contribution.

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### This might not be exactly accurate(due to run time slicing of dataset),but it's still a good starting point to do hts forecasting with low compute resources.
Consider change 'hts' to 'hierarchical time series' unless you define this abbreviation beforehand.

2021-11-23 15:41 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### This might not be exactly accurate(due to run time slicing of dataset),but it's still a good starting point to do hts forecasting with low compute resources.
Could you explain "This might not be exactly accurate(due to run time slicing of dataset)" in more detail? I don't quite get it.

2021-11-23 15:46 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Custom-HTS.ipynb
> +        "# Custom Heirarchical Time Series Forecasting\n",
Please see my comments in the Readme file. I also recommend you take a look at the markdown format in the existing example notebooks of the forecasting repo.

2021-11-23 15:49 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Custom-HTS.ipynb
> +        "\n",
Please put all the import statements in a separate cell.

2021-11-23 16:04 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### Using a standard compute resource (STANDARD_DS11_V2) and traning the model over the dataset provided in the Data folder,took more than 3 hours to train the model.As per the [documentation](https:
@chenhuims , So basically you mean to describe What heirarchial time series forecasting is ? 
Then perhaps a one liner about Azure Ml ? 

Instead of doing so, if I  put up this link : https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-forecast

Wouldn't that be enough ?

2021-11-23 16:05 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Custom-HTS.ipynb
> +        "        #Generating a Unique key name based on the heirarchy combination passed. The key would look like this __state_WA_store_id_1_product_category_B_SKU_B2.csv\n",
Please break this comment into multiple lines for better visibility

2021-11-23 16:05 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### What really happens is that I dynamically slice the dataset basis the heirarchy variables the user passes upon which it requires the forecast for,then using the sliced dataset I train the model a
@chenhuims , I'll correct the typos

2021-11-23 16:06 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### This might not be exactly accurate(due to run time slicing of dataset),but it's still a good starting point to do hts forecasting with low compute resources.
> Consider change 'hts' to 'hierarchical time series' unless you define this abbreviation beforehand.

I'll do the needful 👍

2021-11-23 16:07 UTC, Jash271 commented on examples/Custom Heirarchical Time Series Forecasting/Custom-HTS.ipynb
> +        "        #Generating a Unique key name based on the heirarchy combination passed. The key would look like this __state_WA_store_id_1_product_category_B_SKU_B2.csv\n",
👍

2021-11-23 16:22 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Custom-HTS.ipynb
> +        "- ### train_df_path: path to the training dataset\n",
Please remove ### before each bullet point

2021-11-23 16:24 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Custom-HTS.ipynb
> +            "         date  0.05  0.5  0.9  0.75\n",
Could you compute some evaluation metrics such as rmse, mape, or pinball loss on the results? In addition, it would be great if you can visualize the results.

2021-11-23 16:29 UTC, Jash271 commented
@chenhuims , The problem with evaluation is that in the test dataset, we don't have the actual values with us

2021-11-23 16:29 UTC, chenhuims commented
@Jash271 Thank your for updating the dataset. Please take a look at my additional comments. Besides, I think we should move this example to the [/contrib](https://github.com/microsoft/forecasting/tree/master/contrib) folder based on the current content of the notebook.

2021-11-23 16:30 UTC, Jash271 commented
> @Jash271 Thank your for updating the dataset. Please take a look at my additional comments. Besides, I think we should move this example to the [/contrib](https://github.com/microsoft/forecasting/tree/master/contrib) folder based on the current content of the notebook.

Yes sir ,I'll look to incorporate all the changes as you have suggested.But with respect to the evaluation metric is that we don't have the actual values for the test dataset with which we can compare our results

2021-11-23 16:33 UTC, Jash271 commented
@chenhuims , Sir besides should this could we connect over a teams call, I guess I haven't been able convincingly  put across my point

2021-11-23 16:33 UTC, chenhuims commented
> @chenhuims , The problem with evaluation is that in the test dataset, we don't have the actual values with us

Can you partition the dataset into a training set and a test set so that we can evaluate the results on the test set?

2021-11-23 16:34 UTC, Jash271 commented
> > @chenhuims , The problem with evaluation is that in the test dataset, we don't have the actual values with us
> 
> Can you partition the dataset into a training set and a test set so that we can evaluate the results on the test set?

@chenhuims ,I was just typing this thing out only,was thinking to do this only .

So I'll create another notebook for time being for the results thing

2021-12-02 21:52 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### Using a standard compute resource (STANDARD_DS11_V2) and traning the model over the dataset provided in the Data folder,took more than 3 hours to train the model.As per the [documentation](https:
@Jash271 I was thinking about describing the requirements of your hierarchical forecasting problem such as the aggregation levels of the product demand that you need to forecast, the forecast horizon, the evaluation metrics, etc.

2021-12-02 21:52 UTC, chenhuims commented on examples/Custom Heirarchical Time Series Forecasting/Readme.md
> +### What really happens is that I dynamically slice the dataset basis the heirarchy variables the user passes upon which it requires the forecast for,then using the sliced dataset I train the model a
sounds good

2021-12-08 12:57 UTC, Jash271 commented
> > @chenhuims , The problem with evaluation is that in the test dataset, we don't have the actual values with us
> 
> Can you partition the dataset into a training set and a test set so that we can evaluate the results on the test set?

@chenhuims Azure ML takes care of that and a log with respect to the performance of various models like Arima have been listed. The best model then is chosen for predicting

2021-12-08 20:12 UTC, Jash271 commented
@chenhuims , Sir please have a look now. As suggested by you, I have corrected the Typos and have added the evaluation metrics as well. I am making use of normalized_root_mean_squared_error.

2021-12-11 15:13 UTC, Jash271 commented
@chenhuims Sir any updates ?

2021-12-14 14:43 UTC, Jash271 commented
@chenhuims Sir any updates ?

2021-12-16 22:18 UTC, chenhuims commented
> @chenhuims , Sir please have a look now. As suggested by you, I have corrected the Typos and have added the evaluation metrics as well. I am making use of normalized_root_mean_squared_error.
> 
> Incase, If there's a problem viewing the changes, you could additionally visit this to view the changes here :
> 
> https://github.com/Jash271/forecasting/tree/master/contrib/AzureML%20Custom%20Hierarchical%20Time%20Series%20Forecasting

Thank you for making the changes!

2021-12-16 22:25 UTC, chenhuims commented on contrib/AzureML Custom Hierarchical Time Series Forecasting/Readme.md
> +![Data](./Photos/Data.png)
I suggestion you to name the Photos directory as assets or pics per the convention of this repo

2021-12-16 22:26 UTC, chenhuims commented on contrib/AzureML Custom Hierarchical Time Series Forecasting/Readme.md
> +![Hierarchy Image](./Photos/Hierarchy.PNG)
Rename Hierarchy.PNG to Hierarchy.png would be better

2021-12-16 22:27 UTC, chenhuims commented on contrib/AzureML Custom Hierarchical Time Series Forecasting/Readme.md
> +![Data](./Photos/Data.png)
Similar comments to the `Data` folder - would be better to use lower case `data` instead

2021-12-16 22:33 UTC, chenhuims commented on contrib/AzureML Custom Hierarchical Time Series Forecasting/Readme.md
> +Using a standard compute resource (STANDARD_DS11_V2) and training the model over the dataset provided in the Data folder took more than 3 hours to train the model. As per the [documentation](https://
Hierarchical time series forecasting usually requires forecasting the target values aggregated at different levels, such as the aggregated sales of each state and the aggregated sales of each store. Here if you train the model on all hierarchy combinations, are you able to get the forecasts at different aggregation levels or only the forecasts for each individual store-product? I'm asking this to confirm if you are really doing hierarchical forecasting or just forecasting multiple time series in parallel using AzureML?

2021-12-17 04:58 UTC, Jash271 commented
@chenhuims , I've made the changes and have renamed the folder and pics

2021-12-17 18:36 UTC, chenhuims commented on contrib/README.md
> +| AzureML Custom Hierarchical Time Series Forecasting | An approach to generate hierarchical time series forecasts even with low computational resources within 20 mins |
The running time should be dependent on the data size, number of time series, and many other factors. So I suggest to put "An approach to generate hierarchical time series forecasts with low computational resources".

2021-12-17 18:37 UTC, chenhuims commented on contrib/AzureML Custom Hierarchical Time Series Forecasting/Readme.md
> +The issue is that I wanted forecasts for a very niche set of query, i.e. state=WA,store_id=1,product_category=B, SKU=B2, but I had to wait for the whole traning to get over hence I have come up with
Is this just equivalent to forecasting a single time series? If so, this might not be a good example of hierarchical time series forecasting

2021-12-17 18:45 UTC, chenhuims commented on contrib/AzureML Custom Hierarchical Time Series Forecasting/Custom_Hierarchical_Time_Series_Forecasting.ipynb
> +        "            automl_config = AutoMLConfig(\n",
From this automl_config, it looks that you are just forecasting multiple individual time series in parallel instead of doing hierarchical time series forecasting which requires you to forecast the target variable aggregated at different levels. Could you double check?

2021-12-17 20:03 UTC, Jash271 commented
@chenhuims ,
How about creating a no code application for generating forecasts for a niche query set over a data that has multiple levels of heirarchy.

This could perhaps be a service much like Azure's other services like ocr,custom vision etc. 
Azure currently doesn't have something of this sort to generate time series forecasts .

2023-04-30 21:54 UTC, dciborow approved these changes

2023-04-30 21:54 UTC, merged